---
title: "Fényképészek és fényképészműtermek Magyarországon adatttárának összekapcsolása tudásrendszerekkel"
format: 
   html: default
   gfm: default 
editor: visual
author:
  - name: "Antal, Dániel"
    orcid: 0000-0001-7513-6760
    url: https://reprex.nl/author/daniel-antal/
    affiliations:
      - name: Reprex
        address: "Saturnusstraat 14"
        city: The Hague
        state: Zuid-Holland
        country: The Netherlands
        postal-code: "2516 AH"
        url: https://reprex.nl/
      - name: OpenCollections
        url: https://opencollections.net/
  - name: "Mester, Anna"
  - name: "Sidó, Zsuzsa"
---

## 

1\. Hetente egyszer találkozukn online, amikor Annának kiadunk feladatokat, és átbeszéljük a haldást.

2\. A feladatokat mind OpenRefineban és Excelben kell megoldani. Ehhez Anna ismerkedjen meg az <https://openrefine.org/> eszközzel.

3\. A kész feladatokat egy GitHub repositoryba töltjük fel, és a heti feladatokat ott is vezetjük egyszerű kanban kártyákon.  Ehhez létrehozom a [GitHub repositoryt](https://github.com/dataobservatory-eu/atelier-hungary) (olyasmi mint egy Google Drive folder), A. hozzon létre egy ingyenes GitHub accountot valamilyen professzionáils account névvel, pl. anna.mester etc, amit munkához is fog adott esetben később használni.

4\. A feladatok végrehajtását dokumentáljuk egy olyan cikkben, amit az Apertúra folyóiratban megpróbálunk megjelentetni.  Ennek a szerzője Mester Anna, Sidó Zsuzsa és Antal Dániel lesz  közösen. 

5\. A cikk megírásában A. dokumentálja a lépéseket, amit OpenRefine-ban megtesz, ezeket Zs. mint adatgazdász szakos szupervisor ellenőrzi, szerkesztni, D. pedig hozzáteszi az adat és információtudományi és fotótörténeti dolgokat.  A cikk hivatkozás jegyzékét egy közös Zotero hivatkozáskezelőben vezetjük.  Ehhez Zsuzsa, Anna is rendelkezzen Zotero accounttal (ingyenes).
